services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
    #depends_on:
    #  - web

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node:
    image: node:20-alpine
    container_name: laravel_node
    working_dir: /var/www/html
    #No fa falta, ja farem builds puntuals, sinó genera problemes en producció
    #command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173" # Vite HMR
    volumes:
      - ./:/var/www/html
    depends_on:
      - app